name: "Terraform-Destroy-Infrastructure"

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Terraform Destroy'     
        required: true
        default: 'Success'
      tags:
        description: 'Destroy Infrastructure'
  
jobs:
  terraform:
    name: "Terraform-Destroy-Infrastructure"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          
      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Destroy
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform destroy -auto-approve
